### ISSUE TITLE
Align catkey with cocina model

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sdr-api#125]
Currently, the API handles the catkey in a different way then cocina models. This requires fiddling with it in `resources_controller`:
```
def clean_catkey(model_params)
    catkey = model_params[:identification].delete(:catkey)
    return if catkey.nil?

    model_params[:identification][:catalogLinks] = [{
      catalog: 'symphony',
      catalogRecordId: catkey
    }]
  end
```

Once aligned, this fiddling shouldn't be required.

**Comment by justinlittman** [comment]
@jcoyne @mjgiarlo As I think about this, wondering if we want SDR API fully aligned with cocina models, as it will make the API more complex. That is, arguably a user shouldn't need to understand cocina models to deposit. Having catkey as a field may be a reasonable simplification.

**Comment by jcoyne** [comment]
I would really like to encourage us to standardize on one model as that should reduce our internal complexity.  Most of the consumers of SDR api will be internal anyway (etd, hydrus, google books and maybe pre-assembly, was-registrar and Argo) and having multiple similar, but not the same interfaces will be confusing for developers.

**Comment by justinlittman** [comment]
Then should we simplify the API in cases like this and avoid hypothetical generalization? It seems like a very complex way to specify a catkey.

**Comment by jcoyne** [comment]
For now, understanding that we have a ILS migration on the horizion, we'll keep the complexity.
