### ISSUE TITLE
Mark jp2s for preservation and shelving.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-api#13]
Because assembly-objectfile has assumptions that JP2 are only for shelving.

**Comment by mjgiarlo** [comment]
More generally, I think I heard a requirement that the deposit API allow individual deposits to opt into (of out of?) preservation, shelving, and publication. Confirm/deny/amend? cc: @andrewjbtw

**Comment by andrewjbtw** [comment]
Yes, API users need to be able to make these choices. I don't think we can assume all files in a given deposit will have the same settings.

In the current system, publish/shelve/preserve settings are:

- set by an app that feeds content to SDR (such as hydrus, goobi, and maybe ETD?) 
- set by a manifest submitted for certain content types through pre-assembly (media might be the only one, not sure about 3D)
- set by a glob or regex in the YAML file configuration that is submitted when using lyberservices-scripts (formerly legacy-preassembly)
- set via the settings in assembly-objectfile that are keyed to mimetypes, with a default of preserve-only for file types not on the list of specified mimetypes 
- set by 
    - editing the contentMetadata datastream manually in Argo 
    - restaging the content in /dor/workspace in the appropriate druid tree
    - and then opening and closing the object to run it through the accessionWF again, which re-activates the shelve and publish steps again

**Comment by ndushay** [comment]
what is left to complete this ticket?  What is actionable and what is not yet actionable?

**Comment by mjgiarlo** [comment]
@jcoyne :point_up: still blocked?

**Comment by jcoyne** [comment]
@mjgiarlo blocked?  I don't see anything blocked.  I think this is actionable.

**Comment by ndushay** [comment]
It's in the review/QA column on the zenhub board;  should it be moved to a diff column.

**Comment by mjgiarlo** [comment]
@jcoyne the line just prior to @ndushay's is 
> @jcoyne (Justin Coyne) set this issue as blocked by Api change 23 days ago

**Comment by mjgiarlo** [comment]
@jcoyne can we close the issue?

**Comment by jcoyne** [comment]
It's not blocked and it still needs to be QAed.

**Comment by mjgiarlo** [comment]
@jcoyne ok. who's gonna QA it? is that a you thing or an andrew thing or otherwise?

**Comment by mjgiarlo** [comment]
@jcoyne Has this been QAed yet?

**Comment by andrewjbtw** [comment]
Has this been implemented as a choice? 

For google books, JP2s are  publish/shelve/preserve = yes

But in other circumstances, JP2s will be publish/shelve = yes and preserve = no.

**Comment by jcoyne** [comment]
@andrewjbtw 
I thought we said we don't want to shelve or publish the jp2s because we don't have the disk space on stacks?


Currently our googlebooks jp2s look like this:
```xml
    <file id="00000001.jp2" mimetype="image/jp2" publish="no" shelve="no" preserve="yes" size="124939">...</file>
```

**Comment by andrewjbtw** [comment]
My comments were aimed more at sdr-api usage in general, not the specifics of Google Books.
