### ISSUE TITLE
[sdr-api/stage] KeyError: key not found: "contains"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-api#130]
The code is saying that "structural.contains" is a required field, but it should not be: https://github.com/sul-dlss/cocina-models/blob/master/docs/maps/DRO.json#L261

## Backtrace

    line 19 of [PROJECT_ROOT]/app/controllers/resources_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/67994/faults/61027619)

**Comment by justinlittman** [comment]
This was caused by bad data. I've cleaned it up.
