### ISSUE TITLE
Create demo of how deposit api could be used with an ETD.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-api#135]
Currently it's up to the robots to map the "properties" and "readers" datastreams to Dor objects https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/etd_submit/other_metadata.rb#L27-L30

However, it shouldn't be too hard to show how we could do the same using the API.  Here's an example record: https://argo.stanford.edu/view/druid:cr605kj4725

**Comment by ndushay** [comment]
is this ticket about creating a branch that will appropriately cope with an etd submission?   Presumably after the submission has the abstract, pdf, reader approval, registrar approvel?

**Comment by jcoyne** [comment]
Yeah, this is just a demonstration of what depositing an api would look like, either a script or documentation of how to do it using the CLI.

**Comment by ndushay** [comment]
I believe the properties and readers datastreams are added to the ETD DOR object not by the robots, but by the hydra_etd app:
- "readers" datastream: https://github.com/sul-dlss/hydra_etd/blob/master/app/datastreams/readers_datastream.rb
- "properties" datastream: https://github.com/sul-dlss/hydra_etd/blob/master/app/services/peoplesoft_object_builder.rb 

this code is triggered by a call to the etds_controller in the hydra_etd app, which is actually an endpoint used by the registrar.

If we need to add the data akin to these datastreams as part of the data sent to the sdr-api deposit endpoint ... wouldn't we want to have an etd cocina-model to accommodate these?  (Or, if we don't need to keep these separate as datastreams ... would there be an optional structural component in the DRO model to accommodate them?)

That is -- these are specific datastreams in our current DOR objects ... and I don't see how the sdr-api deposit endpoint is supposed to accommodate the data other than via cocina models.  

If i'm missing the point here, let's try to talk in real time so I can understand the goal of this ticket better.

**Comment by jcoyne** [comment]
I'm not sure that data is valuable, that's just there as temporary data that is put into the generated PDF.
