### ISSUE TITLE
Add an okcomputer check to confirm that the correct number of workers are running

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sdr-api#381]
For apps that use sidekiq, add an okcomputer check to confirm that the correct number of workers are running.  We do a similar thing in some resque-pool using apps (e.g. pres cat).  This is not just a minimum check, but checks that the configured number of workers are present to ensure there are no stale older workers still running unexpectedly.

@jcoyne points us to some useful API documentation:  https://github.com/mperham/sidekiq/wiki/API#workers

This ticket is being added to sdr-api repo, but it could apply to any repo that uses sidekiq.

**Comment by peetucket** [comment]
Took a look at the Sidekiq API, but not fully understanding how things are setup.  

For example, on sdr-api QA:

```
3.0.3 :012 > Sidekiq::Stats.new
 =>
#<Sidekiq::Stats:0x00007fd0244d80e0
 @stats=
  {:processed=>4558774,
   :failed=>1522,
   :scheduled_size=>0,
   :retry_size=>0,
   :dead_size=>4,
   :processes_size=>5,
   :default_queue_latency=>0}>
```

I would presume that `processes_size` is the number of workers, but in `config/sidekiq.yml` it looks like we set concurrency to 6, so should there by 6 workers?

Indeed if you look a the process count manually, there are 5 running:

```
bash-4.2$ ps -ef | grep sidekiq
sdr        452     1  0 Jan18 ?        00:01:34 sidekiq 6.3.1 sdr-api [0 of 6 busy]
sdr        455     1  0 Jan18 ?        00:01:33 sidekiq 6.3.1 sdr-api [0 of 6 busy]
sdr        460     1  0 Jan18 ?        00:01:33 sidekiq 6.3.1 sdr-api [0 of 6 busy]
sdr        465     1  0 Jan18 ?        00:01:35 sidekiq 6.3.1 sdr-api [0 of 6 busy]
sdr        478     1  0 Jan18 ?        00:01:38 sidekiq 6.3.1 sdr-api [0 of 6 busy]
sdr      28978 28741  0 15:20 pts/0    00:00:00 grep --color=auto sidekiq
```

**Comment by jmartin-sul** [comment]
ok, so i think the above described confusion around worker counts has to do with how sidekiq manages workers:  there can be many worker management processes, each with many concurrent worker threads.  `processes_size` corresponds with the processes listed by the `ps` output, and is configured in our environments by puppet.  the concurrency defines the number of worker threads per process, and is set in `config/sidekiq.yml` (the `[0 of 6 busy]` on each worker process in the `ps` output).  the total number of concurrent worker threads is (_i think_) the total number of worker processes times the defined concurrency.

i have a draft PR in hydra_etd (and a supporting puppet PR for hydra_etd stage) that i think gives us a pattern to work off of for this check.
