### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sdr-api#415]
## Backtrace

    line 34 of [PROJECT_ROOT]/app/jobs/ingest_job.rb: rescue in perform
    line 23 of [PROJECT_ROOT]/app/jobs/ingest_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/67994/faults/84388165)

**Comment by jcoyne** [comment]
I suspect this is a RoundtripValidationError in DSA. That raises a `conflict` (409), but does not follow the expected format of having a druid. https://github.com/sul-dlss/dor-services-app/blob/2ac9d78e999eb9a738a8c887d0b6e2f0ce726730/app/validators/cocina/roundtrip_validation_error.rb#L7

**Comment by justinlittman** [comment]
This is still occurring. If you take a closer look, the regex doesn't match the error message:
`/\((druid:.{11})\)/` for `Dor::Services::Client::ConflictResponse: Conflict: 409 ({"errors":[{"status":"409","title":"Conflict","detail":"An object ([\"druid:kd533vd3674\"]) with the source ID 'googlebooks:stanford_36105110994782' has already been registered."}]})`

**Comment by jcoyne** [comment]
It looks like the problem is this method returns an array rather than a scalar: https://github.com/sul-dlss/dor-services-app/blob/9e08e5d74dca90075de63922596d1e0d69dd40bf/app/validators/cocina/unique_source_id_validator.rb#L37-L43
