### ISSUE TITLE
Add role=transcription for hOCR files

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-api#45]
in the contentMetadata.

**Comment by jcoyne** [comment]
@jermnelson you will find that this is something we can add to the API after https://github.com/sul-dlss/sdr-api/pull/96 is merged

**Comment by jermnelson** [comment]
Issue moved to [sul-dlss/google-books #197](https://github.com/sul-dlss/google-books/issues/197) via [**ZenHub**](https://www.zenhub.com/)
