### ISSUE TITLE
Download files from Globus to workspace

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/sdr-api#526]
We will be using Globus as a means to transfer large files to SDR via H2. Instead of needing many components within SDR to be connected to Globus, we'd like to limit Globus awareness to sdr-api. 

# What's needed

- [x] Add `globus_client` as a dependency
- [ ] When creating or updating a resource, accept one or more new globus-related params giving the `globus_client` the information it needs to find the files (will a directory path e.g. `/uploads/username/work123/version1` suffice?)
- [ ] Set the directory containing the files to read-only (blocked by sul-dlss/globus_client#36)
- [ ] Use this information + the necessary Globus configuration† to download the files and stash them in the DOR workspace
- [ ] Test and verify that what comes back works with recent HFS changes if the filenames expose hierarchy

† This would be a globus client ID and a globus client secret---both of which live in vault (e.g., `vault kv get puppet/application/h2/globus/client_id` & `vault kv get puppet/application/h2/globus/client_secret`)---and also a globus endpoint ID (`34ea3e65-6831-479a-8da3-87f118e3fc2b` for QA, with stage and prod coming soon) and a base directory (`/uploads/`)---both of which could live in `shared_configs` for `sdr-api`.

# Analysis

If helpful, feel free to review the [analysis](https://github.com/sul-dlss/dor-services-app/issues/4270)

**Comment by justinlittman** [comment]
One possible approach is: When constructing the cocina structural metadata, H2 provides a namespaced external identifier that indicates the file's location on globus mount. This is similar to how H2 indicates to SDR API that a file should be copied from ActiveStorage.

**Comment by mjgiarlo** [comment]
@aaron-collier Is this still in progress or should it be closed?

**Comment by mjgiarlo** [comment]
@aaron-collier ☝🏻
