### ISSUE TITLE
update openapi.yml to remove references to symphony

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sdr-api#610]
After sul-dlss/cocina-models/issues/614, 
- [ ] update openapi.yml 
- [ ] search on, case insensitive, e.g.:
    - [ ] `catalogRecordId`
    - [ ] `catalog_record_id`
    - [ ] `ckey`
    - [ ] `catkey`
    - [ ] `symphony`
    - [ ] `ils`
    - [ ] `folio`
    - [ ] ...

**Comment by edsu** [comment]
From planning: This is redundant with our normal release process that will be performed as part of #614.

**Comment by ndushay** [comment]
this is NOT done.   See https://github.com/search?q=repo%3Asul-dlss%2Fcocina-models%20symphony&type=code

**Comment by ndushay** [comment]
nm - i'm an idiot.
