### ISSUE TITLE
Algorithimically determine book rights based on catalog metadata

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sdr-api#63]
Based on discussions about sul-dlss/google-books#1, we have come up with the following approach:

1. Using the symphony lookup service API (currently available in dor-services-app?), fetch marc XML for the given barcode/catkey.  Alternatively - use the marcxml file in the google books download package.
1. Look at publication year in mac, if (PUB_YEAR < 1890) OR (PUB_YEAR < (CURRENT_YEAR - 96) AND IMPRINT_COUNTRY == USA), rights can be public.
1. If not OR if pub year is not available, rights are citation only and then set embargo as below
1. if IMPRINT_COUNTRY == USA and PUB_YEAR > (CURRENT_YEAR - 95), set embargo to release to public domain for PUB_YEAR - (CURRENT_YEAR - 96) + CURRENT_YEAR
1. if IMPRINT_COUNTRY != USA or unknown, set embargo to release to public domain for PUB_YEAR - (CURRENT_YEAR - 130) + CURRENT_YEAR
1. Then lookup visibility as determined by google (need API reference here) and log if this is different than our computation

**Comment by jcoyne** [comment]
Issue moved to [sul-dlss/google-books #103](https://github.com/sul-dlss/google-books/issues/103) via [**ZenHub**](https://www.zenhub.com/)
