### ISSUE TITLE
Configure disk storage directory so it's not overwritten

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-api#79]
Currently disk storage is configured as `/opt/app/sdr/sdr-api/releases/{release}/storage`  however we have capistrano set to wipe out old releases (keeping the most recent 5).  We need to move it elsewhere so the files are not overwritten.

**Comment by peetucket** [comment]
We can move it to the "shared" folder and then add it to the `linked_dirs` section in the cap `deploy.rb` just like the log folder.
